name: Build, Lint, and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout and setup environment
              uses: MetaMask/action-checkout-and-setup@v1
              with:
                  is-high-risk-environment: false
            - name: Build
              run: yarn build
            - name: Upload Snap build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: snap-${{ runner.os }}-${{ github.sha }}
                  path: ./packages/snap/dist
                  retention-days: 1
            - name: Upload Shared build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: shared-${{ runner.os }}-${{ github.sha }}
                  path: ./packages/shared/dist
                  retention-days: 1

    lint:
        name: Lint
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Checkout and setup environment
              uses: MetaMask/action-checkout-and-setup@v1
              with:
                  is-high-risk-environment: false
            - name: Download Shared build artifact
              uses: actions/download-artifact@v4
              with:
                  name: shared-${{ runner.os }}-${{ github.sha }}
                  path: ./packages/shared/dist
            - name: Lint
              run: yarn lint

    test:
        name: Test
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Checkout and setup environment
              uses: MetaMask/action-checkout-and-setup@v1
              with:
                  is-high-risk-environment: false
            - name: Download Snap build artifact
              uses: actions/download-artifact@v4
              with:
                  name: snap-${{ runner.os }}-${{ github.sha }}
                  path: ./packages/snap/dist
            - name: Download Shared build artifact
              uses: actions/download-artifact@v4
              with:
                  name: shared-${{ runner.os }}-${{ github.sha }}
                  path: ./packages/shared/dist
            - name: Run e2e tests
              run: yarn test
